<?php

return [
    'morocco' => [
        'regions' => [
            'tanger_tetouan_al_hoceima' => [
                'name' => 'Tanger-Tétouan-Al Hoceïma',
                'name_ar' => 'طنجة تطوان الحسيمة',
                'cities' => [
                    'tanger' => ['name' => 'Tanger', 'name_ar' => 'طنجة'],
                    'tetouan' => ['name' => 'Tétouan', 'name_ar' => 'تطوان'],
                    'al_hoceima' => ['name' => 'Al Hoceïma', 'name_ar' => 'الحسيمة'],
                    'chefchaouen' => ['name' => 'Chefchaouen', 'name_ar' => 'شفشاون'],
                    'larache' => ['name' => 'Larache', 'name_ar' => 'العرائش'],
                    'ksar_el_kebir' => ['name' => 'Ksar El Kébir', 'name_ar' => 'القصر الكبير'],
                    'ouezzane' => ['name' => 'Ouezzane', 'name_ar' => 'وزان'],
                    'fnideq' => ['name' => 'Fnideq', 'name_ar' => 'الفنيدق'],
                    'mdiq' => ['name' => 'M\'diq', 'name_ar' => 'المضيق'],
                    'martil' => ['name' => 'Martil', 'name_ar' => 'مارتيل'],
                    'asilah' => ['name' => 'Asilah', 'name_ar' => 'أصيلة'],
                    'souk_el_arbaa_du_rharb' => ['name' => 'Souk El Arbaa du Rharb', 'name_ar' => 'سوق الأربعاء الغرب'],
                    'bni_bouayach' => ['name' => 'Bni Bouayach', 'name_ar' => 'بني بوعياش'],
                    'imzouren' => ['name' => 'Imzouren', 'name_ar' => 'إمزورن'],
                    'bni_ansar' => ['name' => 'Bni Ansar', 'name_ar' => 'بني انصار'],
                    'zaio' => ['name' => 'Zaïo', 'name_ar' => 'زايو'],
                ],
            ],
            'oriental' => [
                'name' => 'Oriental',
                'name_ar' => 'الشرق',
                'cities' => [
                    'oujda' => ['name' => 'Oujda', 'name_ar' => 'وجدة'],
                    'berkane' => ['name' => 'Berkane', 'name_ar' => 'بركان'],
                    'nador' => ['name' => 'Nador', 'name_ar' => 'الناظور'],
                    'taourirt' => ['name' => 'Taourirt', 'name_ar' => 'تاوريرت'],
                    'guercif' => ['name' => 'Guercif', 'name_ar' => 'جرسيف'],
                    'figuig' => ['name' => 'Figuig', 'name_ar' => 'فجيج'],
                    'driouch' => ['name' => 'Driouch', 'name_ar' => 'الدريوش'],
                    'jerada' => ['name' => 'Jerada', 'name_ar' => 'جرادة'],
                    'al_aroui' => ['name' => 'Al Aroui', 'name_ar' => 'العروي'],
                    'ahfir' => ['name' => 'Ahfir', 'name_ar' => 'أحفير'],
                    'beni_drar' => ['name' => 'Beni Drar', 'name_ar' => 'بني درار'],
                    'el_aioun_sidi_mellouk' => ['name' => 'El Aioun Sidi Mellouk', 'name_ar' => 'العيون سيدي ملوك'],
                    'tendrara' => ['name' => 'Tendrara', 'name_ar' => 'تندرارة'],
                    'debdou' => ['name' => 'Debdou', 'name_ar' => 'دبدو'],
                    'selouane' => ['name' => 'Selouane', 'name_ar' => 'سلوان'],
                    'bni_chiker' => ['name' => 'Bni Chiker', 'name_ar' => 'بني شيكر'],
                    'midar' => ['name' => 'Midar', 'name_ar' => 'ميدار'],
                    'ras_el_ma' => ['name' => 'Ras El Ma', 'name_ar' => 'رأس الماء'],
                    'talsint' => ['name' => 'Talsint', 'name_ar' => 'تالسينت'],
                    'bouarfa' => ['name' => 'Bouarfa', 'name_ar' => 'بوعرفة'],
                ],
            ],
            'fes_meknes' => [
                'name' => 'Fès-Meknès',
                'name_ar' => 'فاس مكناس',
                'cities' => [
                    'fes' => ['name' => 'Fès', 'name_ar' => 'فاس'],
                    'meknes' => ['name' => 'Meknès', 'name_ar' => 'مكناس'],
                    'taza' => ['name' => 'Taza', 'name_ar' => 'تازة'],
                    'sefrou' => ['name' => 'Sefrou', 'name_ar' => 'صفرو'],
                    'el_hajeb' => ['name' => 'El Hajeb', 'name_ar' => 'الحاجب'],
                    'ifrane' => ['name' => 'Ifrane', 'name_ar' => 'إفران'],
                    'azrou' => ['name' => 'Azrou', 'name_ar' => 'أزرو'],
                    'boulemane' => ['name' => 'Boulemane', 'name_ar' => 'بولمان'],
                    'moulay_yacoub' => ['name' => 'Moulay Yacoub', 'name_ar' => 'مولاي يعقوب'],
                    'imouzzer_kandar' => ['name' => 'Imouzzer Kandar', 'name_ar' => 'إموزار كندر'],
                    'bouknadel' => ['name' => 'Bouknadel', 'name_ar' => 'بوقنادل'],
                    'ribat_el_kheir' => ['name' => 'Ribat El Kheir', 'name_ar' => 'رباط الخير'],
                    'guigou' => ['name' => 'Guigou', 'name_ar' => 'كيكو'],
                    'ain_taoujdate' => ['name' => 'Aïn Taoujdate', 'name_ar' => 'عين تاوجطات'],
                    'mrhassiyine' => ['name' => 'Mrhassiyine', 'name_ar' => 'مرحاسيين'],
                    'sebt_jamaa' => ['name' => 'Sebt Jamaa', 'name_ar' => 'سبت جماعة'],
                    'oulad_tayeb' => ['name' => 'Oulad Tayeb', 'name_ar' => 'أولاد طيب'],
                    'sabaa_aiyoun' => ['name' => 'Sabaa Aiyoun', 'name_ar' => 'سبعة عيون'],
                    'karia_ba_mohamed' => ['name' => 'Karia Ba Mohamed', 'name_ar' => 'قرية با محمد'],
                    'ghouazi' => ['name' => 'Ghouazi', 'name_ar' => 'غوازي'],
                    'hattane' => ['name' => 'Hattane', 'name_ar' => 'حطان'],
                    'tahla' => ['name' => 'Tahla', 'name_ar' => 'تاهلة'],
                ],
            ],
            'rabat_sale_kenitra' => [
                'name' => 'Rabat-Salé-Kénitra',
                'name_ar' => 'الرباط سلا القنيطرة',
                'cities' => [
                    'rabat' => ['name' => 'Rabat', 'name_ar' => 'الرباط', 'is_capital' => true],
                    'sale' => ['name' => 'Salé', 'name_ar' => 'سلا'],
                    'kenitra' => ['name' => 'Kénitra', 'name_ar' => 'القنيطرة'],
                    'temara' => ['name' => 'Temara', 'name_ar' => 'تمارة'],
                    'skhirat' => ['name' => 'Skhirat', 'name_ar' => 'الصخيرات'],
                    'sidi_kacem' => ['name' => 'Sidi Kacem', 'name_ar' => 'سيدي قاسم'],
                    'sidi_slimane' => ['name' => 'Sidi Slimane', 'name_ar' => 'سيدي سليمان'],
                    'khemisset' => ['name' => 'Khémisset', 'name_ar' => 'الخميسات'],
                    'tiflet' => ['name' => 'Tiflet', 'name_ar' => 'تيفلت'],
                    'rommani' => ['name' => 'Rommani', 'name_ar' => 'رماني'],
                    'sidi_yahya_zaer' => ['name' => 'Sidi Yahya Zaer', 'name_ar' => 'سيدي يحيى زعير'],
                    'ain_el_aouda' => ['name' => 'Aïn El Aouda', 'name_ar' => 'عين العودة'],
                    'harhoura' => ['name' => 'Harhoura', 'name_ar' => 'هرهورة'],
                    'oulmes' => ['name' => 'Oulmès', 'name_ar' => 'ولماس'],
                    'sidi_allal_el_bahraoui' => ['name' => 'Sidi Allal El Bahraoui', 'name_ar' => 'سيدي علال البحراوي'],
                    'sidi_bouknadel' => ['name' => 'Sidi Bouknadel', 'name_ar' => 'سيدي بوقنادل'],
                    'sidi_taibi' => ['name' => 'Sidi Taibi', 'name_ar' => 'سيدي طيبي'],
                    'arbaoua' => ['name' => 'Arbaoua', 'name_ar' => 'أرباوة'],
                    'moulay_bousselham' => ['name' => 'Moulay Bousselham', 'name_ar' => 'مولاي بوسلهام'],
                    'beni_malik' => ['name' => 'Beni Malik', 'name_ar' => 'بني مالك'],
                    'dar_bel_amri' => ['name' => 'Dar Bel Amri', 'name_ar' => 'دار بلعمري'],
                ],
            ],
            'beni_mellal_khenifra' => [
                'name' => 'Béni Mellal-Khénifra',
                'name_ar' => 'بني ملال خنيفرة',
                'cities' => [
                    'beni_mellal' => ['name' => 'Béni Mellal', 'name_ar' => 'بني ملال'],
                    'khenifra' => ['name' => 'Khénifra', 'name_ar' => 'خنيفرة'],
                    'khouribga' => ['name' => 'Khouribga', 'name_ar' => 'خريبكة'],
                    'fquih_ben_salah' => ['name' => 'Fquih Ben Salah', 'name_ar' => 'الفقيه بن صالح'],
                    'kasba_tadla' => ['name' => 'Kasba Tadla', 'name_ar' => 'قصبة تادلة'],
                    'ouaouizeght' => ['name' => 'Ouaouizeght', 'name_ar' => 'واويزغت'],
                    'el_ksiba' => ['name' => 'El Ksiba', 'name_ar' => 'القصيبة'],
                    'ait_ouchen' => ['name' => 'Aït Ouchen', 'name_ar' => 'آيت أوشن'],
                    'aghbala' => ['name' => 'Aghbala', 'name_ar' => 'أغبالة'],
                    'zaouiat_cheikh' => ['name' => 'Zaouiat Cheikh', 'name_ar' => 'زاوية الشيخ'],
                    'oulad_ayad' => ['name' => 'Oulad Ayad', 'name_ar' => 'أولاد عياد'],
                    'sebt_ait_rahou' => ['name' => 'Sebt Ait Rahou', 'name_ar' => 'سبت آيت راحو'],
                    'sidi_jaber' => ['name' => 'Sidi Jaber', 'name_ar' => 'سيدي جابر'],
                    'dar_oulad_zidouh' => ['name' => 'Dar Oulad Zidouh', 'name_ar' => 'دار أولاد زيدوح'],
                    'bradia' => ['name' => 'Bradia', 'name_ar' => 'براضية'],
                    'boujniba' => ['name' => 'Boujniba', 'name_ar' => 'بوجنيبة'],
                    'mrirt' => ['name' => 'M\'rirt', 'name_ar' => 'مريرت'],
                    'tighassaline' => ['name' => 'Tighassaline', 'name_ar' => 'تيغساليين'],
                    'ait_ishaq' => ['name' => 'Ait Ishaq', 'name_ar' => 'آيت إسحاق'],
                ],
            ],
            'casablanca_settat' => [
                'name' => 'Casablanca-Settat',
                'name_ar' => 'الدار البيضاء سطات',
                'cities' => [
                    'casablanca' => ['name' => 'Casablanca', 'name_ar' => 'الدار البيضاء', 'is_major' => true],
                    'settat' => ['name' => 'Settat', 'name_ar' => 'سطات'],
                    'mohammedia' => ['name' => 'Mohammédia', 'name_ar' => 'المحمدية'],
                    'el_jadida' => ['name' => 'El Jadida', 'name_ar' => 'الجديدة'],
                    'benslimane' => ['name' => 'Benslimane', 'name_ar' => 'بنسليمان'],
                    'berrechid' => ['name' => 'Berrechid', 'name_ar' => 'برشيد'],
                    'sidi_bennour' => ['name' => 'Sidi Bennour', 'name_ar' => 'سيدي بنور'],
                    'nouaceur' => ['name' => 'Nouaceur', 'name_ar' => 'النواصر'],
                    'mediouna' => ['name' => 'Médiouna', 'name_ar' => 'مديونة'],
                    'lahraouyine' => ['name' => 'Lahraouyine', 'name_ar' => 'الهراويين'],
                    'dar_bouazza' => ['name' => 'Dar Bouazza', 'name_ar' => 'دار بوعزة'],
                    'ben_ahmed' => ['name' => 'Ben Ahmed', 'name_ar' => 'بن أحمد'],
                    'oulad_abbou' => ['name' => 'Oulad Abbou', 'name_ar' => 'أولاد عبو'],
                    'zemamra' => ['name' => 'Zemamra', 'name_ar' => 'زمامرة'],
                    'oualidia' => ['name' => 'Oualidia', 'name_ar' => 'الوليدية'],
                    'azemmour' => ['name' => 'Azemmour', 'name_ar' => 'أزمور'],
                    'bir_jdid' => ['name' => 'Bir Jdid', 'name_ar' => 'بير جديد'],
                    'el_borouj' => ['name' => 'El Borouj', 'name_ar' => 'البروج'],
                    'guisser' => ['name' => 'Guisser', 'name_ar' => 'كيسر'],
                    'had_soualem' => ['name' => 'Had Soualem', 'name_ar' => 'حد السوالم'],
                    'loulad' => ['name' => 'Loulad', 'name_ar' => 'لولاد'],
                    'oulad_hriz_sahel' => ['name' => 'Oulad H\'Riz Sahel', 'name_ar' => 'أولاد حريز الساحل'],
                    'sidi_rahhal' => ['name' => 'Sidi Rahhal', 'name_ar' => 'سيدي رحال'],
                    'tit_mellil' => ['name' => 'Tit Mellil', 'name_ar' => 'تيط مليل'],
                    'bejaad' => ['name' => 'Bejaad', 'name_ar' => 'بجعد'],
                ],
            ],
            'marrakech_safi' => [
                'name' => 'Marrakech-Safi',
                'name_ar' => 'مراكش آسفي',
                'cities' => [
                    'marrakech' => ['name' => 'Marrakech', 'name_ar' => 'مراكش', 'is_major' => true],
                    'safi' => ['name' => 'Safi', 'name_ar' => 'آسفي'],
                    'essaouira' => ['name' => 'Essaouira', 'name_ar' => 'الصويرة'],
                    'youssoufia' => ['name' => 'Youssoufia', 'name_ar' => 'اليوسفية'],
                    'el_kelaa_des_sraghna' => ['name' => 'El Kelâa des Sraghna', 'name_ar' => 'قلعة السراغنة'],
                    'chichaoua' => ['name' => 'Chichaoua', 'name_ar' => 'شيشاوة'],
                    'rehamna' => ['name' => 'Rehamna', 'name_ar' => 'الرحامنة'],
                    'benguerir' => ['name' => 'Benguérir', 'name_ar' => 'بنجرير'],
                    'sidi_bou_othmane' => ['name' => 'Sidi Bou Othmane', 'name_ar' => 'سيدي بوعثمان'],
                    'ait_ourir' => ['name' => 'Ait Ourir', 'name_ar' => 'آيت أورير'],
                    'tahannaout' => ['name' => 'Tahannaout', 'name_ar' => 'تحناوت'],
                    'amizmiz' => ['name' => 'Amizmiz', 'name_ar' => 'أميزميز'],
                    'demnate' => ['name' => 'Demnate', 'name_ar' => 'دمنات'],
                    'el_kelaa' => ['name' => 'El Kelaâ', 'name_ar' => 'القلعة'],
                    'sidi_smaiil' => ['name' => 'Sidi Smai\'il', 'name_ar' => 'سيدي اسماعيل'],
                    'jemaat_shaim' => ['name' => 'Jemaat Shaim', 'name_ar' => 'جماعة شعيم'],
                    'sebt_gzoula' => ['name' => 'Sebt Gzoula', 'name_ar' => 'سبت كزولة'],
                    'smimou' => ['name' => 'Smimou', 'name_ar' => 'سميمو'],
                    'bouabout' => ['name' => 'Bouabout', 'name_ar' => 'بوعبوط'],
                    'ighoud' => ['name' => 'Ighoud', 'name_ar' => 'إغود'],
                    'laattaouia' => ['name' => 'Laattaouia', 'name_ar' => 'العطاوية'],
                    'sidi_abdelkader' => ['name' => 'Sidi Abdelkader', 'name_ar' => 'سيدي عبد القادر'],
                    'tamanar' => ['name' => 'Tamanar', 'name_ar' => 'تامنار'],
                    'zaouiat_ben_hmida' => ['name' => 'Zaouiat Ben Hmida', 'name_ar' => 'زاوية بن حميدة'],
                ],
            ],
            'draa_tafilalet' => [
                'name' => 'Drâa-Tafilalet',
                'name_ar' => 'درعة تافيلالت',
                'cities' => [
                    'errachidia' => ['name' => 'Errachidia', 'name_ar' => 'الراشيدية'],
                    'ouarzazate' => ['name' => 'Ouarzazate', 'name_ar' => 'ورزازات'],
                    'tinghir' => ['name' => 'Tinghir', 'name_ar' => 'تنغير'],
                    'zagora' => ['name' => 'Zagora', 'name_ar' => 'زاكورة'],
                    'midelt' => ['name' => 'Midelt', 'name_ar' => 'ميدلت'],
                    'boumalne_dades' => ['name' => 'Boumalne Dadès', 'name_ar' => 'بومالن دادس'],
                    'kelaat_mgouna' => ['name' => 'Kelaat M\'Gouna', 'name_ar' => 'قلعة مكونة'],
                    'tinejdad' => ['name' => 'Tinejdad', 'name_ar' => 'تنجداد'],
                    'alnif' => ['name' => 'Alnif', 'name_ar' => 'النيف'],
                    'jorf' => ['name' => 'Jorf', 'name_ar' => 'جرف'],
                    'gourrama' => ['name' => 'Gourrama', 'name_ar' => 'كورامة'],
                    'rissani' => ['name' => 'Rissani', 'name_ar' => 'الريصاني'],
                    'erfoud' => ['name' => 'Erfoud', 'name_ar' => 'أرفود'],
                    'ait_benhaddou' => ['name' => 'Aït Benhaddou', 'name_ar' => 'آيت بن حدو'],
                    'skoura' => ['name' => 'Skoura', 'name_ar' => 'صكورة'],
                    'tazarine' => ['name' => 'Tazarine', 'name_ar' => 'تازارين'],
                    'nkob' => ['name' => 'N\'Kob', 'name_ar' => 'نقوب'],
                    'boudnib' => ['name' => 'Boudnib', 'name_ar' => 'بودنيب'],
                    'goulmima' => ['name' => 'Goulmima', 'name_ar' => 'كلميمة'],
                    'imilchil' => ['name' => 'Imilchil', 'name_ar' => 'إميلشيل'],
                    'itzer' => ['name' => 'Itzer', 'name_ar' => 'إتزر'],
                    'mssici' => ['name' => 'M\'ssici', 'name_ar' => 'مسيسي'],
                    'outat_el_haj' => ['name' => 'Outat El Haj', 'name_ar' => 'وطاط الحاج'],
                    'zawyat_sidi_hamza' => ['name' => 'Zawyat Sidi Hamza', 'name_ar' => 'زاوية سيدي حمزة'],
                ],
            ],
            'souss_massa' => [
                'name' => 'Souss-Massa',
                'name_ar' => 'سوس ماسة',
                'cities' => [
                    'agadir' => ['name' => 'Agadir', 'name_ar' => 'أكادير', 'is_major' => true],
                    'inezgane' => ['name' => 'Inezgane', 'name_ar' => 'إنزكان'],
                    'ait_melloul' => ['name' => 'Aït Melloul', 'name_ar' => 'آيت ملول'],
                    'taroudant' => ['name' => 'Taroudant', 'name_ar' => 'تارودانت'],
                    'tiznit' => ['name' => 'Tiznit', 'name_ar' => 'تزنيت'],
                    'oulad_teima' => ['name' => 'Oulad Teima', 'name_ar' => 'أولاد تايمة'],
                    'biougra' => ['name' => 'Biougra', 'name_ar' => 'بيوكرى'],
                    'ait_baha' => ['name' => 'Aït Baha', 'name_ar' => 'آيت باها'],
                    'belfaa' => ['name' => 'Belfaa', 'name_ar' => 'بلفاع'],
                    'bigoudine' => ['name' => 'Bigoudine', 'name_ar' => 'بيكودين'],
                    'bouizakarne' => ['name' => 'Bouizakarne', 'name_ar' => 'بويزكارن'],
                    'el_guerdane' => ['name' => 'El Guerdane', 'name_ar' => 'الكردان'],
                    'irherm' => ['name' => 'Irherm', 'name_ar' => 'إرهرم'],
                    'ouijjane' => ['name' => 'Ouijjane', 'name_ar' => 'ويجان'],
                    'sebt_el_guerdane' => ['name' => 'Sebt El Guerdane', 'name_ar' => 'سبت الكردان'],
                    'sidi_bibi' => ['name' => 'Sidi Bibi', 'name_ar' => 'سيدي بيبي'],
                    'tafraout' => ['name' => 'Tafraout', 'name_ar' => 'تافراوت'],
                    'temsia' => ['name' => 'Temsia', 'name_ar' => 'تمسية'],
                    'chtouka_ait_baha' => ['name' => 'Chtouka-Aït Baha', 'name_ar' => 'شتوكة آيت باها'],
                ],
            ],
            'guelmim_oued_noun' => [
                'name' => 'Guelmim-Oued Noun',
                'name_ar' => 'كلميم واد نون',
                'cities' => [
                    'guelmim' => ['name' => 'Guelmim', 'name_ar' => 'كلميم'],
                    'sidi_ifni' => ['name' => 'Sidi Ifni', 'name_ar' => 'سيدي إفني'],
                    'tan_tan' => ['name' => 'Tan-Tan', 'name_ar' => 'طانطان'],
                    'assa' => ['name' => 'Assa', 'name_ar' => 'أسا'],
                    'fam_el_hisn' => ['name' => 'Fam El Hisn', 'name_ar' => 'فم الحصن'],
                    'taghjijt' => ['name' => 'Taghjijt', 'name_ar' => 'تاغجيجت'],
                    'mirleft' => ['name' => 'Mirleft', 'name_ar' => 'ميرلفت'],
                    'akka' => ['name' => 'Akka', 'name_ar' => 'أقا'],
                    'tata' => ['name' => 'Tata', 'name_ar' => 'طاطا'],
                ],
            ],
            'laayoune_sakia_el_hamra' => [
                'name' => 'Laâyoune-Sakia El Hamra',
                'name_ar' => 'العيون الساقية الحمراء',
                'cities' => [
                    'laayoune' => ['name' => 'Laâyoune', 'name_ar' => 'العيون'],
                    'boujdour' => ['name' => 'Boujdour', 'name_ar' => 'بوجدور'],
                    'tarfaya' => ['name' => 'Tarfaya', 'name_ar' => 'طرفاية'],
                    'smara' => ['name' => 'Smara', 'name_ar' => 'السمارة'],
                    'el_marsa' => ['name' => 'El Marsa', 'name_ar' => 'المرسى'],
                ],
            ],
            'dakhla_oued_ed_dahab' => [
                'name' => 'Dakhla-Oued Ed-Dahab',
                'name_ar' => 'الداخلة وادي الذهب',
                'cities' => [
                    'dakhla' => ['name' => 'Dakhla', 'name_ar' => 'الداخلة'],
                    'aousserd' => ['name' => 'Aousserd', 'name_ar' => 'أوسرد'],
                    'bir_gandouz' => ['name' => 'Bir Gandouz', 'name_ar' => 'بير كندوز'],
                    'guerguerat' => ['name' => 'Guerguerat', 'name_ar' => 'الكركرات'],
                ],
            ],
        ],

        // Quick access to major cities
        'major_cities' => [
            'casablanca' => ['name' => 'Casablanca', 'name_ar' => 'الدار البيضاء', 'region' => 'casablanca_settat'],
            'rabat' => ['name' => 'Rabat', 'name_ar' => 'الرباط', 'region' => 'rabat_sale_kenitra', 'is_capital' => true],
            'marrakech' => ['name' => 'Marrakech', 'name_ar' => 'مراكش', 'region' => 'marrakech_safi'],
            'fes' => ['name' => 'Fès', 'name_ar' => 'فاس', 'region' => 'fes_meknes'],
            'tanger' => ['name' => 'Tanger', 'name_ar' => 'طنجة', 'region' => 'tanger_tetouan_al_hoceima'],
            'agadir' => ['name' => 'Agadir', 'name_ar' => 'أكادير', 'region' => 'souss_massa'],
            'meknes' => ['name' => 'Meknès', 'name_ar' => 'مكناس', 'region' => 'fes_meknes'],
            'oujda' => ['name' => 'Oujda', 'name_ar' => 'وجدة', 'region' => 'oriental'],
            'kenitra' => ['name' => 'Kénitra', 'name_ar' => 'القنيطرة', 'region' => 'rabat_sale_kenitra'],
            'tetouan' => ['name' => 'Tétouan', 'name_ar' => 'تطوان', 'region' => 'tanger_tetouan_al_hoceima'],
            'safi' => ['name' => 'Safi', 'name_ar' => 'آسفي', 'region' => 'marrakech_safi'],
            'mohammedia' => ['name' => 'Mohammédia', 'name_ar' => 'المحمدية', 'region' => 'casablanca_settat'],
            'khouribga' => ['name' => 'Khouribga', 'name_ar' => 'خريبكة', 'region' => 'beni_mellal_khenifra'],
            'beni_mellal' => ['name' => 'Béni Mellal', 'name_ar' => 'بني ملال', 'region' => 'beni_mellal_khenifra'],
            'el_jadida' => ['name' => 'El Jadida', 'name_ar' => 'الجديدة', 'region' => 'casablanca_settat'],
            'taza' => ['name' => 'Taza', 'name_ar' => 'تازة', 'region' => 'fes_meknes'],
            'nador' => ['name' => 'Nador', 'name_ar' => 'الناظور', 'region' => 'oriental'],
            'settat' => ['name' => 'Settat', 'name_ar' => 'سطات', 'region' => 'casablanca_settat'],
            'larache' => ['name' => 'Larache', 'name_ar' => 'العرائش', 'region' => 'tanger_tetouan_al_hoceima'],
            'khenifra' => ['name' => 'Khénifra', 'name_ar' => 'خنيفرة', 'region' => 'beni_mellal_khenifra'],
        ],
    ],
];
